### ISSUE TITLE
gepetto-gui issue with boost 1.69.0?

### ISSUE THREAD

**Issue by jviereck** [Gepetto/homebrew-gepetto#2]
Hi folks,

a student using macOS installed boost 1.69.0 via homebrew. After installing gepetto-viewer and starting gepetto-gui, this error appeared:

```
 gepetto-gui
dyld: Symbol not found: __ZN5boost11basic_regexIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9do_assignEPKcS7_j
	Referenced from: /usr/local/bin/gepetto-gui
	Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
	in /usr/local/bin/gepetto-gui
Abort trap: 6
```

We resolved this by manually copy-paste the libraries from my 1.68. installation :/

**Comment by jcarpent** [comment]
@jviereck Sorry, I've just seen your issue. Is it still open?

**Comment by jviereck** [comment]
To be hones, I don't know. I haven't tried it lately.

Is someone up for giving it a try? Otherwise I will try to reproduce with a brew installation and see if it still shows up.

**Comment by jviereck** [comment]
Haven't tested it. Closing for now for sake of time. If someone runs into this, happy to look closer into it once more.
