### ISSUE TITLE
Update to version python3.8 for gepetto-viewer-corba-python3 and omniorbpy.rb?

### ISSUE THREAD

**Issue by jviereck** [Gepetto/homebrew-gepetto#3]
A previous commit bumped the python version for pinocchio to 3.8. However, the other packages using python `omniorbpy.rb` and `gepetto-viewer-corba-python3` rely on python3, which can get resolved to python3.7. This causes then troubles when using the latest pinocchio on python 3.8 and trying to use gepetto at the same time.

Would it therefore make sense to bump the python version in gepetto and omniorbpy as well?

**Comment by jcarpent** [comment]
Yes, we can do it. Sorry for the late reply.

**Comment by jcarpent** [comment]
Done!

**Comment by jviereck** [comment]
Thanks!
