### ISSUE TITLE
Bump version of hpp-fcl?

### ISSUE THREAD

**Issue by jviereck** [Gepetto/homebrew-gepetto#7]
I would like to use the latest version of hpp-fcl (1.7.5). The version used in the bottle is 1.6.0.

Any chance the bottle could be updated to match the latest release of hpp-fcl?

**Comment by jcarpent** [comment]
I will proceed.

**Comment by jcarpent** [comment]
Issue solved. Please pull from recent commit 445b7e9.

**Comment by jviereck** [comment]
Thanks @jcarpent for updating the bottles!
